### PR TITLE
Minor updates, $http.get URLs, and SAS section.

### PR DESCRIPTION
**Pull request by darkape**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Which issues does this PR fix?

**Comment by mmoayyed** [comment]
Are these the issues addressed in this PR? Issues #32, #35, #37, #38, #39, #40. Issues #28, #40 based on the commit messages?

**Comment by darkape** [comment]
Yes, all of the issues that are addressed in the PR should be able to be closed. If we update the Service DELETE and D&D UPDATE $http.get to $http.post, then it is a minor update that we could wait for this PR or just add it in the next.

**Comment by mmoayyed** [comment]
OK thanks. I'll test this one first and open another for changing the method to POST

**Pull request merged**
